rubocop:
  config_file: .rubocop.yml
  # This should stay in line with the version resolved in the Gemfile.lock,
  # which you can verify with `bundle info rubocop`.
  #
  # Notice that Hound supports only a subset of the RuboCop versions. You can
  # find the list of supported versions here:
  # http://help.houndci.com/en/articles/2461415-supported-linters
  version: 0.75.0
