# yaml-language-server: $schema=https://raw.githubusercontent.com/buildkite/pipeline-schema/main/schema.json
---

steps:
  #################
  # Build and Test
  #################
  - group: 🧪 Build and Test"
    key: test
    steps:
      - label: "🧪 Build and Test using Ruby {{ matrix.ruby }}"
        command: |
          echo "--- :ruby: Using ruby {{ matrix.ruby }}"
          export RBENV_VERSION={{ matrix.ruby }}
          ruby --version

          echo "--- :package: Installing homebrew packages"
          # We only need this for tasks running on a Mac
          brew install pkg-config git-lfs libxml2 imagemagick@6

          echo "--- :git: Setting up git-lfs"
          git-lfs install

          echo "--- :rubygems: Setting up Gems"
          install_gems

          echo "--- :rspec: Run Rspec"
          bundle exec rspec --profile 10 --format progress
        env:
          IMAGE_ID: $IMAGE_ID
        plugins:
          - $CI_TOOLKIT_PLUGIN
        agents:
          queue: "mac"
        matrix:
          setup:
            ruby:
              - $RUBY_VERSION

  #################
  # Push to RubyGems
  #################
  - label: ":rubygems: Publish to RubyGems"
    key: "gem-push"
    if: build.tag != null
    depends_on:
     - test
    # Note: We intentionally call a separate `.sh` script here (as opposed to having all the
    # commands written inline) to avoid leaking a key used in the process in clear in the
    # BUILDKITE_COMMAND environment variable.
    command: .buildkite/commands/gem-push.sh
    plugins:
      - docker#v5.8.0:
          image: "public.ecr.aws/docker/library/ruby:$RUBY_VERSION"
          propagate-environment: true
          environment:
            - "RUBYGEMS_API_KEY"
    agents:
      queue: "default"
