#!/bin/bash

export IMAGE_ID="xcode-26.1.1"
export CI_TOOLKIT="automattic/a8c-ci-toolkit#3.7.1"
export DOCKER_PLUGIN="docker#v5.8.0"
export RUBY_VERSION="3.2.2"
export DOCKER_RUBY_IMAGE="public.ecr.aws/docker/library/ruby:$RUBY_VERSION"
