# frozen_string_literal: true

require 'gettext'
require 'gettext/po_parser'
require 'gettext/po'
require 'twitter_cldr'

module Fastlane
  module Helper
    class FluentLocalizationHelper
      # Represents a parsed Fluent entry
      FluentEntry = Struct.new(:key, :value, :comment, :line_number) do
        def initialize(key:, value:, comment: nil, line_number: nil)
          super(key, value, comment, line_number)
        end
      end

      # Parse a Fluent (.ftl) file and return an array of FluentEntry objects
      def self.parse_fluent_file(file_path)
        entries = []
        current_comment = nil

        File.readlines(file_path, encoding: 'utf-8').each_with_index do |line, index|
          line = line.strip
          line_number = index + 1

          # Reset comment when encountering blank lines
          if line.empty?
            current_comment = nil
            next
          end

          # Handle comments
          if line.start_with?('#')
            current_comment = current_comment ? "#{current_comment}\n#{line[1..].strip}" : line[1..].strip
            next
          end

          # Handle key-value pairs
          next unless line.include?('=')

          key, value = line.split('=', 2)
          key = key.strip
          value = value.strip

          entries << FluentEntry.new(
            key: key,
            value: value,
            comment: current_comment,
            line_number: line_number
          )

          current_comment = nil
        end

        entries
      end

      # Convert Fluent entries to PO format
      def self.fluent_to_po(fluent_file:, fluent_entries:, locale:, project_name:, project_version:)
        po = GetText::PO.new

        # Create header entry
        header_content = generate_po_header(locale: locale, project_name: project_name, project_version: project_version)
        header_entry = GetText::POEntry.new(:normal)
        header_entry.msgid = ''
        header_entry.msgstr = header_content
        header_entry.translator_comment = "Generated by #{Fastlane::Wpmreleasetoolkit::NAME} (#{Fastlane::Wpmreleasetoolkit::VERSION})"
        po[nil, ''] = header_entry

        fluent_entries.each do |entry|
          po_entry = GetText::POEntry.new(:normal)
          po_entry.msgid = entry.key
          po_entry.msgstr = entry.value
          po_entry.references = ["#{fluent_file}:#{entry.line_number}"]
          po_entry.translator_comment = entry.comment

          po[nil, entry.key] = po_entry
        end

        # Format options for output
        format_options = {
          max_line_width: -1
        }

        po.to_s(format_options)
      end

      # Parse a PO (.po) file and return array of entries
      def self.parse_po_file(file_path)
        po = GetText::PO.new
        parser = GetText::POParser.new
        parser.ignore_fuzzy = false
        parser.report_warning = true
        parser.parse_file(file_path, po)

        # Filter out header entry and return only translated entries
        po.entries.reject { |entry| entry.msgid.to_s.empty? }
      end

      # Convert PO entries back to Fluent format
      def self.po_to_fluent(po_entries)
        fluent_content = ''

        po_entries.each do |entry|
          # Skip untranslated entries
          next if entry.msgstr.to_s.empty?

          # Add translator comments if present
          if entry.translator_comment && !entry.translator_comment.to_s.empty?
            entry.translator_comment.to_s.split("\n").each do |comment_line|
              next if comment_line.strip.empty?

              fluent_content += "# #{comment_line.strip}\n"
            end
          end

          # Add the Fluent entry
          fluent_content += "#{entry.msgid} = #{entry.msgstr}\n"
          fluent_content += "\n"
        end

        fluent_content
      end

      # Generate PO file header lines for GetText::PO
      def self.generate_po_header(locale:, project_name:, project_version:)
        timestamp = Time.now.strftime('%Y-%m-%d %H:%M%z')
        plural_rule = get_plural_rule(locale)

        [
          "Project-Id-Version: #{project_name} #{project_version}\n",
          "POT-Creation-Date: #{timestamp}\n",
          "PO-Revision-Date: #{timestamp}\n",
          "Language: #{locale}\n",
          "MIME-Version: 1.0\n",
          "Content-Type: text/plain; charset=UTF-8\n",
          "Content-Transfer-Encoding: 8bit\n",
          "Plural-Forms: #{plural_rule || 'nplurals=2; plural=(n != 1);'}\n",
        ].join
      end

      # Check if a string contains Fluent variables (e.g., {$variable})
      def self.contains_variables?(text)
        text.match?(/\{\$[^}]+\}/)
      end

      # Get plural rule for a locale using TwitterCLDR data
      def self.get_plural_rule(locale)
        # Normalize locale (e.g., en-US -> en, pt-BR -> pt)
        lang_code = locale.split('-').first.to_sym

        # Get plural categories for the language from TwitterCldr
        plural_categories = TwitterCldr::Formatters::Plurals::Rules.all_for(lang_code)
        return nil if plural_categories.empty?

        nplurals = plural_categories.length

        # Use a simple mapping based on the number of plural categories
        # This covers the most common cases without hardcoding complex expressions
        case nplurals
        when 1
          # Languages like Chinese, Japanese, Korean
          'nplurals=1; plural=0;'
        when 3
          # Slavic languages (Russian, Polish, etc.)
          # Use a generic 3-form rule that works for most Slavic languages
          'nplurals=3; plural=(n%10==1 && n%100!=11 ? 0 : n%10>=2 && n%10<=4 && (n%100<10 || n%100>=20) ? 1 : 2);'
        when 4
          # Languages like Slovenian
          'nplurals=4; plural=(n%100==1 ? 0 : n%100==2 ? 1 : n%100==3 || n%100==4 ? 2 : 3);'
        when 6
          # Arabic and a few other languages
          'nplurals=6; plural=(n==0 ? 0 : n==1 ? 1 : n==2 ? 2 : n%100>=3 && n%100<=10 ? 3 : n%100>=11 ? 4 : 5);'
        else
          # Most Germanic and Romance languages (English, German, Spanish, etc.) and fallback
          'nplurals=2; plural=(n != 1);'
        end
      rescue StandardError
        # If TwitterCldr fails for any reason, fallback to English-style rule
        'nplurals=2; plural=(n != 1);'
      end
    end
  end
end
